#import <HSWidgets/HSWidgetCombinedAdditionalOptionsAndPreferencesViewController.h>

@interface HSWeatherWidgetPreferencesViewController : HSWidgetCombinedAdditionalOptionsAndPreferencesViewController
@end